app/models/__init__.py
# models/__init__.py

class Link:
    def __init__(self, url):
        self.url = url

app/__init__.py
from flask import Flask
from app.controllers.main_controller import main_controller

app = Flask(__name__)

# Registrar o controlador
app.register_blueprint(main_controller)

if __name__ == '__main__':
    app.run(debug=True)

app/controllers/default.py
from app import app


@app.route("/")
def index():
    return "Hello"

app/controllers/main_controller.py
from flask import Blueprint, render_template, request
import google.generativeai as genai
from app.senha import GEMINI_API_KEY
from bs4 import BeautifulSoup
import requests

main_controller = Blueprint('main_controller', __name__)

# Configure a chave da API do Gemini
genai.configure(api_key=GEMINI_API_KEY)

@main_controller.route('/')
def index():
    return render_template('index.html')

@main_controller.route('/', methods=['POST'])
def scrape():
    url = request.form['url']
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Levanta um erro para códigos de status 4xx ou 5xx
        
        # Usar BeautifulSoup para analisar o conteúdo HTML
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Extrair texto de todas as tags <p>
        paragraphs = soup.find_all('p')
        page_content = '\n'.join([p.get_text() for p in paragraphs])  # Juntar todos os textos em uma única string
        
        # Use a API do Gemini para gerar uma resposta
        model = genai.GenerativeModel('gemini-1.5-flash')
        result = model.generate_content(f"Resuma o texto em no máx 100 palavras, não passe disso:\n\n{page_content}")
        
        summary = result.text.strip()
        
    except requests.exceptions.RequestException as e:
        page_content = f"Erro ao acessar a URL: {str(e)}"
        summary = ""
    except Exception as e:
        page_content = "Ocorreu um erro interno no servidor."
        summary = f"Erro interno no servidor: {str(e)}"
    
    return render_template('index.html', page_content=page_content, summary=summary)

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Link Reader</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <h1>Link Reader</h1>
        <p class="description">Insira uma URL e obtenha um resumo do conteúdo em poucos segundos.</p>
        <hr>
    </header>
    <main>
        
            <section class="form-section">
                <form id="urlForm" action="{{ url_for('main_controller.scrape') }}" method="post" onsubmit="showLoading()">
                    <label for="url">Digite a URL do site:</label>
                    <input type="text" id="url" name="url" required>
                    <button type="submit">Resumir</button>
                </form>
                <div id="loading" class="loading" style="display: none;">
                    Carregando...
                </div>
            </section>
            
            {% if summary %}
            <section class="result-section">
                <div class="result-div">
                    <h2>Resumo:</h2>
                    <p>{{ summary }}</p>
                </div>
                
            </section>
            {% endif %}
        </div>
    </main>

    <script>
        function showLoading() {
            document.getElementById('loading').style.display = 'block';
        }
    </script>
</body>
</html>